version: '3.8'
services:
  app:
    container_name: daily_words
    build: .
    working_dir: /app
    ports:
      - '3200:3000'
    env_file:
      - .env
    environment:
      - WORD_DIFFCIULTY_URL=http://word-dfficulty:8000
    restart: unless-stopped
    # depends_on:
    #   - word-difficulty
    networks:
      - global
  # word-difficulty:
  #   build:
  #     context: ./word_difficulty
  #     dockerfile: Dockerfile
  #   container_name: word-difficulty
  #   ports:
  #     - '8000:8000'
  #   environment:
  #     - SUBTLEX_PATH=/data
  #     - PORT=8000
  #   volumes:
  #     - ./word_difficulty/data:/data
  #   restart: unless-stopped
  #   networks:
networks:
  app-net:
    external: true
